import type { Knex } from 'knex'

exports.up = async function (knex: Knex): Promise<void> {
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-01.json' })
    .where({ id: 1 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-02.json' })
    .where({ id: 2 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-03.json' })
    .where({ id: 3 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-04.json' })
    .where({ id: 4 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-05.json' })
    .where({ id: 5 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-06.json' })
    .where({ id: 6 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-07.json' })
    .where({ id: 7 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-08.json' })
    .where({ id: 8 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-09.json' })
    .where({ id: 9 })
  await knex('exams')
    .update({ url: 'https://dkmwdxc6g4lk7.cloudfront.net/exams/exam-10.json' })
    .where({ id: 10 })
}

exports.down = async function (knex: Knex): Promise<void> {
  await knex('exams').update({ url: '' }).where({ id: 1 })
  await knex('exams').update({ url: '' }).where({ id: 2 })
  await knex('exams').update({ url: '' }).where({ id: 3 })
  await knex('exams').update({ url: '' }).where({ id: 4 })
  await knex('exams').update({ url: '' }).where({ id: 5 })
  await knex('exams').update({ url: '' }).where({ id: 6 })
  await knex('exams').update({ url: '' }).where({ id: 7 })
  await knex('exams').update({ url: '' }).where({ id: 8 })
  await knex('exams').update({ url: '' }).where({ id: 9 })
  await knex('exams').update({ url: '' }).where({ id: 10 })
}
